### ISSUE TITLE
After running this sample locally, I did not report any errors, but the table below still did not display it. However, the sample on the official website can display normally. Why is this? Sorry to bother you, thank you for providing the software with care

### ISSUE THREAD

**Issue by zhoushangdeng** [DHTMLX/gantt#103]
This is the sample address on the official website: https://docs.dhtmlx.com/gantt/samples/?sample=%2702_extensions/22_tooltip_api.html%27&filter=%27custom%20too%27
<img width="1440" alt="image" src="https://github.com/DHTMLX/gantt/assets/54345813/f77d0c84-7ad3-4ea4-8b2c-20c05a5a5636">

This is a screenshot of me： <img width="1440" alt="image" src="https://github.com/DHTMLX/gantt/assets/54345813/55f3df3c-f01d-446b-924d-2677548ab881">

**Comment by gearcoded** [comment]
@zhoushangdeng, the resource load and histogram views work only in the Pro version:
https://docs.dhtmlx.com/gantt/desktop__resource_management.html

Right now, Gantt doesn't inform that this feature is not available in the GPL version, but in the future, the dev team will add a way to do that.
