### ISSUE TITLE
401 UnAuthorized

### ISSUE THREAD

**Issue by bplus0** [DHTMLX/gantt#12]
I'm getting a 401 Not Authorized on Chrome when I try to update a task, and a "Object doesn't support property or method 'selectNodes'" on statement **return c.selectNodes(b)** on Internet Explorer, all related to gantt.min.js. I don't know if there is an issue with my JavaScript file, or what could have happened.

**Comment by AlexKlimenkov** [comment]
Hi,
Looks like the server side issue, not enough info to give a more specific reply.
I'm closing the issue, if it's still actual - please attach some demo and reopen.
