### ISSUE TITLE
Terrible expirience

### ISSUE THREAD

**Issue by mmbfreitas** [DHTMLX/gantt#120]
We are trying to implement gantt using 8.0 pro and it has a lot of bugs, we can't do anything without facing a problem. And the worst of all, the support is very bad and slow, it almost never responds, when it responds it is not objectively, we are willing to pay for the product, but it seems that the company doesn't care much about it

Bugs that we are facing:

* Duration back to 1 when drag
* Task disappears when drag
* A lot of issues with date time

**Comment by maximilianfixl** [comment]
We just stopped while integrating it. The trail repo isn't available anymore and the free test version is not running in Vue 3 CAPI. Maybe I could manage it, but I'm looking for a solution, not for a challenge.

**Comment by AlexKlimenkov** [comment]
@maximilianfixl I've just tested the latest free version of Gantt from [npmjs.com](https://www.npmjs.com/package/dhtmlx-gantt) in a Vue 3.5.12 project using Composition API and it seems to be working as expected, so this issue appears to be fixed.

@mmbfreitas Our team does their best to assist clients within our standard response times during business hours, and we aim to provide helpful solutions to any issues that arise. From what I can see, our support agents responded to your inquiries in customer support system and offered suggestions to address the problems you mentioned.

It seems that, despite our efforts, our library was not the best fit for your project's specific needs. We appreciate your willingness to give us a chance and regret that we couldn't meet your expectations.
