### ISSUE TITLE
Does this component support moving task across the porjects?

### ISSUE THREAD

**Issue by qihuagaosh** [DHTMLX/gantt#121]
Thank guys in advance for this great project.
Does this component support moving task across the porjects?

**Comment by gearcoded** [comment]
**@qihuagaosh **,
Thank you for the positive feedback!
You can vertically reorder tasks in the grid and change the task's parent project:
https://docs.dhtmlx.com/gantt/desktop__reordering_tasks.html

Here are the samples:
https://docs.dhtmlx.com/gantt/samples/07_grid/14_branch_ordering_highlight.html

https://docs.dhtmlx.com/gantt/samples/07_grid/08_drag_between_levels.html

You can also do that with the Gantt API by using the `moveTask` method:
https://docs.dhtmlx.com/gantt/api__gantt_movetask.html

Here is an example:
https://snippet.dhtmlx.com/00wz6qlu
