### ISSUE TITLE
Time axis expansion problem

### ISSUE THREAD

**Issue by z-h2o** [DHTMLX/gantt#123]
How to set the timeline to not automatically expand and only display from the start time to the end time.
![image](https://github.com/user-attachments/assets/8c87f7bb-c6a1-4ed7-8bf8-2eb63e660e09)
As shown in the style above, without automatic extension at both ends

**Comment by gearcoded** [comment]
**@lzwStore**,
By default Gantt adds 1 scale unit to the most right and left task dates. If you want to change how it works, you need to manually set the displayed date range by using the `gantt.config.start_date` and `gantt.config.end_date` parameters:
https://docs.dhtmlx.com/gantt/api__gantt_start_date_config.html

You can check how it works in the following snippet:
https://snippet.dhtmlx.com/o66hmfpf
