### ISSUE TITLE
Warning: "end value has mixed support, consider using flex-end instead"

### ISSUE THREAD

**Issue by rance9879** [DHTMLX/gantt#130]
When building the project, a warning message appears indicating that the end value has mixed support and suggests considering using flex-end instead
Our project require no warnings,If i replace end with flex-end and start with flex-start will cause problems?

**Comment by AlexKlimenkov** [comment]
Yes, you can freely replace it, there was no specific reason for using `start`/`end` instead of `flex-start`/`flex-end`.
We'll do the same changes on our end so it will be a part of the next bugfix update.

**Comment by gearcoded** [comment]
**@rance9879**,
The issue should be fixed in the 9.0.3 version:
https://docs.dhtmlx.com/gantt/whatsnew.html#:~:text=Resolve%20build%20warnings%20from%20PostCSS%20caused%20by%20the%20usage%20of%20%27start%27/%27end%27%20instead%20of%20%27flex%2Dstart%27/%27flex%2Dend%27
