### ISSUE TITLE
Drag n drop semantics with order_branch are different than the sample

### ISSUE THREAD

**Issue by tylerjwatson** [DHTMLX/gantt#14]
Hi guys,

I have a gantt chart with small data of the following prototype: 

```json
{
  "data": [
    {
      "id": 840,
      "duration": 1,
      "open": true,
      "parent": 0,
      "progress": 0,
      "start_date": "23-02-2017",
      "text": "1. Acquire Bagel2"
    },
    {
      "id": 841,
      "duration": 1,
      "open": true,
      "parent": 839,
      "progress": 0,
      "start_date": "28-02-2017",
      "text": "3. Become the bagel"
    },
    {
      "id": 839,
      "duration": 1,
      "open": true,
      "parent": 840,
      "progress": 0,
      "start_date": "25-02-2017",
      "text": "2. Consume Bagel"
    }
  ],
  "links": [
    {
      "id": 118,
      "source": 840,
      "target": 839,
      "type": 0
    },
    {
      "id": 119,
      "source": 839,
      "target": 841,
      "type": 0
    }
  ]
}
```

And the drag and drop experience is considerably different in the GPL version vs the sample on the website.  I draw your attention to the [sample here](https://docs.dhtmlx.com/gantt/samples/07_grid/08_drag_between_levels.html).  The drag experience on the sample places the dragged task in an overlay which follows the mouse and orders tasks on the drop surface out from underneath it, but I cannot replicate this functionality on the GPL version.

* ![Sample version with expected behaviour](https://cloud.githubusercontent.com/assets/5001408/23389079/98ca52ee-fdb1-11e6-8c4d-ce8919479345.gif)
* ![GPL Version (mine)](https://cloud.githubusercontent.com/assets/5001408/23389152/031413d8-fdb2-11e6-9369-20f9faf22518.gif)

Have I missed something, or is this a pro-only feature?

Once again, thank you for your assistance. :)

Cheers,
T.

**Comment by AlexKlimenkov** [comment]
Hi,
vertical drag and drop should work the same way in all editions of gantt. Samples on the website may work a bit differently since sometimes we update them with bugfix builds, but it doesn't seem to be the case now.
Right now I'm not sure what may cause the different behavior, I'll look into the issue soon and will give you an update

**Comment by AlexKlimenkov** [comment]
Hi,
as we haven't discovered anything new so far, so I'm closing the issue
