### ISSUE TITLE
mysqli-support

### ISSUE THREAD

**Issue by christianh95** [DHTMLX/gantt#16]
Is it right that the connector only supports mysql but not mysqli? On my webserver, there is only the php _mysqli_ module installed and I don't have the possibility to install the old _mysql_ module (which is deprecated as far as I know). Is there a way to use _mysqli_?

**Comment by AlexKlimenkov** [comment]
We use dhtmlxConnector for php samples, they support different database drivers:
https://docs.dhtmlx.com/connector__php__server_side_sample.html

Here is how PDO or MySQLi configuration may look like,
connection:
```
// PDO
require_once ("/connector/db_pdo.php");
$res = new PDO("mysql:host=192.168.1.251;dbname=schedulertest", "scheduler", "scheduler");
$dbtype = "PDO";
```
OR
```
// MySQLi
require_once ("/connector/db_mysqli.php");
$res = new mysqli("192.168.1.251", "scheduler", "scheduler", "schedulertest");
$dbtype = "MySQLi";
```
connector:
```
require_once ('/connector/gantt_connector.php');
$gantt = new JSONGanttConnector($res, $dbtype);
$gantt->mix("open", 1);
//$gantt->enable_order("sortorder");

$gantt->render_links("gantt_links_enddate", "id", "source,target,type");
$gantt->render_table("gantt_tasks_enddate","id","start_date,end_date,text,progress,parent","");
```
