### ISSUE TITLE
Grouping extension

### ISSUE THREAD

**Issue by jameshowe** [DHTMLX/gantt#19]
Library appears to be missing the `dhtmlxgantt_grouping.js` extension.

https://docs.dhtmlx.com/gantt/desktop__grouping.html

**Comment by AlexKlimenkov** [comment]
Hi,
dhtmlxgantt_grouping.js is not included into Standard/GPL version of the library which is published here, it's only included in Pro builds (Commercial/Enterprise/Evaluation packages)
