### ISSUE TITLE
Initial_scroll fix

### ISSUE THREAD

**Issue by reniefoxx** [DHTMLX/gantt#20]
In the dhtmlxgantt.js in gantt._process_loading string "var id = (this._order[0]  || this.config.root_id);" should be replaced by "var id = (this.config.root_id || this._order[0]);", otherwise config.root_id is not used.

**Comment by AlexKlimenkov** [comment]
Hello,
should be fixed in the latest version
https://github.com/DHTMLX/gantt/blob/5.0.5/codebase/sources/dhtmlxgantt.js#L12259
