### ISSUE TITLE
While one tasks has more souces,the links can't display

### ISSUE THREAD

**Issue by constanine** [DHTMLX/gantt#21]
@AlexKlimenkov 
scene: data.json
```
{
     "data":....,
     "links":[
                ...
		{"id":"5","source":"1","target":"5","type":"1"},
		{"id":"6","source":"1","target":"6","type":"1"},
		{"id":"7","source":"5,6","target":"7","type":"0"},
                ...
	]
}
```
In this case,the links will not show

However,I check code,maybe function `this._task_area_renderers[id].render_item` (near line 3207) should think multi-sources.
Now,my code like:
```
container = container || node;

if(filter){
	if(!filter(item)){
		this.remove_item(item.id);
		return;
	}
}

var link_sources = [];
if(item.source){
	link_sources = item.source.split(",");
}
if(link_sources.length>1){
	for(var sIdx=0;sIdx<link_sources.length;sIdx++){
		var splitItem = item;
		splitItem.source = link_sources[sIdx];
		var dom = render_one.call(gantt, item);
		this.append(splitItem,dom, container);
	}
}else{
	var dom = render_one.call(gantt, item);
	this.append(item, dom, container);
}
```
Moreover,the function `this._task_area_renderers[id].append` (near line 3255 after above-mentioned modified) should also think about multi-sources
```
if(!node){
	if(this.rendered[item.id]){
		this.remove_item(item.id);
	}
	return;
}
if(item.source){
	if(this.rendered[item.id+"."+item.source] && this.rendered[item.id+"."+item.source].parentNode){
		this.replace_item(item.id, node);
	}else{
		container.appendChild(node);
	}
	this.rendered[item.id+"."+item.source] = node;
}else{
	if(this.rendered[item.id] && this.rendered[item.id].parentNode){
		this.replace_item(item.id, node);
	}else{
		container.appendChild(node);
	}
	this.rendered[item.id] = node;
}
```
Moreover,the function `gantt._filter_link` (near line 3462 after above-mentioned modified) should also think about multi-sources
```
if(!this.config.show_links){
	return false;
}
var link_sources = link.source.split(",");
if(link_sources.length>1){
	var cando = true;
	for(var sIdx=0;sIdx<link_sources.length;sIdx++){			
		if(!gantt.isTaskVisible(link_sources[sIdx])){
			cando = false;
			return false;
		}
	}
	if(!cando){
		return false;
	}
	if(!gantt.isTaskVisible(link.target)){
		return false;
	}
}else{
	if(!(gantt.isTaskVisible(link.source) && gantt.isTaskVisible(link.target)) ||
	gantt._isAllowedUnscheduledTask(gantt.getTask(link.source)) || 
	gantt._isAllowedUnscheduledTask(gantt.getTask(link.target)))
	return false;
}
return this.callEvent("onBeforeLinkDisplay", [id, link]);
```
At Last,this picture is the result of my modify code,wish you will refer it
![multi-sources](https://user-images.githubusercontent.com/7012545/28457361-62504f8c-6e38-11e7-8ca7-5ce0d89290a0.png)

**Comment by AlexKlimenkov** [comment]
Hi,
sorry for not replying earlier.
Currently, we don't plan to add the support of multi-source/multi-target links to gantt, each link should have one source and one target task.
While this may be useful, but adding basic support will complicate code a bit and can create new issues - e.g. there is no ready UI for the user to create such links, and what should happen if user double-clicks one of the lines (line between one of the sources and a target) of such link and decides to delete it - should we delete the whole link (i.e. delete it from all sources/targets), or should we only disconnect the specific source/target user clicked one - which of these will be logical and intuitive for the user.
So currently we'll go with supporting links with one source and one target only, and if a task needs multiple predecessors - it would mean creating several individual links between each predecessor and the task.
