### ISSUE TITLE
MongodB support?

### ISSUE THREAD

**Issue by scheung38** [DHTMLX/gantt#22]
Using Python Flask and Pymongo to talk to MongodB, so I like to know is there support for MongodB? I would like to see demo connecting, loading, editing and making changes from the user interactively, but I don't see my examples.

**Comment by AlexKlimenkov** [comment]
Hi,
dhtmlxGantt is 100% client-side component and is not aware what db you use on the backend.
Technically there is no limitations for using it with mongo, but we don't have any ready demos or tutorials

You can check some general docs on backend implementation
https://docs.dhtmlx.com/gantt/desktop__server_side.html
and tutorials with the examples for different platforms:
https://docs.dhtmlx.com/gantt/desktop__howtostart_guides.html
