### ISSUE TITLE
How to add a responsible person when adding an activity?

### ISSUE THREAD

**Issue by eduardobelchior** [DHTMLX/gantt#23]

**Comment by AlexKlimenkov** [comment]
Hi,
you can add any custom property to gantt items and store the assigned person id there (e.g. task.owner_id). Then in the ui you can add a control mapped to that property into the details form https://docs.dhtmlx.com/gantt/desktop__select.html
and display person name in custom column of the grid using a template https://docs.dhtmlx.com/gantt/desktop__specifying_columns.html#settingthetemplateofdatapresentation
You can find an example in this tutorial, check "Adding List of Users" paragraph https://dhtmlx.com/blog/using-d3-visualize-workload-dhtmlxgantt/
