### ISSUE TITLE
range of year

### ISSUE THREAD

**Issue by yzl-china** [DHTMLX/gantt#32]
The earliest year is 2013~2023? How to add earlier time, and later

**Comment by AlexKlimenkov** [comment]
Hi,
year selector shows `[currentYear - 5, currentYear +5]` by default. You can show different years using `year_range` setting

```
gantt.config.lightbox.sections = [
    {name:"description", height:38, map_to:"text", type:"textarea", focus:true},
    {name:"period",type:"time", map_to:"auto", year_range: [2010, 2025}
];
```

https://docs.dhtmlx.com/gantt/desktop__time.html#properties
https://docs.dhtmlx.com/gantt/desktop__duration.html#properties
