### ISSUE TITLE
set working hours as minutes

### ISSUE THREAD

**Issue by ogazioglu** [DHTMLX/gantt#34]
We can't set our real working hours correctly. Our working periods are

1. 07:30-12:00
2. (lunch break for 30 minutes)
3. 12:30-17:30 

Your API takes hours only as

    gantt.setWorkTime({day : 5, hours : [8,12]})
If you replace integer hours with hour and minutes array we set our hours like below

    gantt.setWorkTime({day : 5, hours : [ [7,30] , [12,00], [12,30], [17,30]  ]})
or

    gantt.setWorkTime({day : 5, hours : [ [7,30] , 12, [12,30], [17,30]  ]})
to backward compatibility with checking item is array.

**Comment by AlexKlimenkov** [comment]
Hi,
it's this feature is in our todo list, however I can't give you any ETA.
Right now it's not planned for the nearest update (v6.2, June 2019), but it still can make into that release.

**Comment by gearcoded** [comment]
Hello,
The dev team added the feature that allows specifying the work time in minutes:
https://docs.dhtmlx.com/gantt/desktop__working_time.html#globalsettings
You can see how it works in the following sample:
https://docs.dhtmlx.com/gantt/samples/09_worktime/11_working_hours_with_minutes.html
