### ISSUE TITLE
Getting error in console 

### ISSUE THREAD

**Issue by mujtaba1016** [DHTMLX/gantt#35]
![image](https://user-images.githubusercontent.com/30212397/54686979-52283b00-4b3c-11e9-95f4-48847c90d1ed.png)

I am getting this error in console

**Comment by AlexKlimenkov** [comment]
Hi,
please provide some kind of a demo so I could reproduce the error.
For example, you can fork this snippet http://next.plnkr.co/edit/AGETc9ejfTHQpJ0t?preview and add necessary code for the error to happen. 
If the error can't be reproduced with an online snippet, I'll need either a repo or zipped demo package which I could download and run locally

**Comment by AlexKlimenkov** [comment]
I'm closing the issue due to inactivity. Feel free to reopen it when you'll have a demo where the error could be reproduced
