### ISSUE TITLE
Dynamic Loading (on demand) Support custom request

### ISSUE THREAD

**Issue by yansenlei** [DHTMLX/gantt#37]
Server-side customization is required in the example: [desktop__dynamic_loading](https://docs.dhtmlx.com/gantt/desktop__dynamic_loading.html)
How to implement dynamic loading child-tasks in a custom way, only client-side.

```js
axios({
  url: 'query/gantt?parent=12',
}).then(res => {
  gantt.addTask(res.data)
})
```

**Comment by AlexKlimenkov** [comment]
Hi,
try using  `gantt.parse`:

```
axios({
  url: 'query/gantt?parent=12',
}).then(res => {
  gantt.parse(res.data)
})
```

demo: http://snippet.dhtmlx.com/8ab63aa31
