### ISSUE TITLE
OT: are the other products available on GitHub?

### ISSUE THREAD

**Issue by dandv** [DHTMLX/gantt#4]
I would love to see DHTMLX Suite available on GitHub, since it's GPLv2-licensed. Is there a repo somewhere?

We're evaluating DHTMLX for use [in a Google project](https://github.com/reciprocity/ggrc-core), and GitHub presence plays an important role. So far, [Webix](https://github.com/webix-hub) and [Kendo UI Core](https://github.com/telerik/kendo-ui-core) have an advantage.

**Comment by AlexKlimenkov** [comment]
A bit late reply, but there is dhtmlxSuite repo on github:
https://github.com/DHTMLX/dhtmlx-suite-gpl

dhtmlxScheduler repo is here as well
https://github.com/DHTMLX/scheduler
