### ISSUE TITLE
[Dhtmlx Gantt pro version].

### ISSUE THREAD

**Issue by kiraka42** [DHTMLX/gantt#40]
In the pro version since the Gantt 6.1.1 version Pacakge.json in gantt is totally different and is now 
fom backend stuff , this is dangeurous because an upgrade of the lib might broke all the project because of this changement.

**Comment by AlexKlimenkov** [comment]
Hi,
we've corrected package structure in the dev branch, it will be published tomorrow in v6.1.7 bugfix update. The package.json in the zip package root will be similar to the one from v6.1.1
