### ISSUE TITLE
Dhtmlx-gantt upgrade to 6.1.8 or more gantt rendering is incomplete

### ISSUE THREAD

**Issue by CodeDreamfy** [DHTMLX/gantt#45]
**version：6.1.8**

### question
I use dhtmlx-gantt for initial rendering. When the number of tasks exceeds 15, the image rendered by gantt is only fixed at 15, after the 15th is all blank, nothing is displayed, but the position is still retained, check the element found. Not rendered

[Click to view image](https://wx4.sinaimg.cn/mw690/a918db34ly1g74tittqn2j21bt0fcq7t.jpg)

**Comment by AlexKlimenkov** [comment]
Hi,

The link you provided gives me `403 Forbidden` error - http://prntscr.com/p87pyv

Can you pls share a complete demo which I could use to reproduce the issue locally?
I'm afraid we won't do any bugfixes for 6.1.x versions, but if I could reproduce it in the latest build (6.2.6 currently) we'll investigate and will work on a solution

**Comment by CodeDreamfy** [comment]
> Hi,
> 
> The link you provided gives me `403 Forbidden` error - http://prntscr.com/p87pyv
> 
> Can you pls share a complete demo which I could use to reproduce the issue locally?
> I'm afraid we won't do any bugfixes for 6.1.x versions, but if I could reproduce it in the latest build (6.2.6 currently) we'll investigate and will work on a solution

hi，he example is not a good demonstration, you can try it first, I will get a demo later.

**Comment by AlexKlimenkov** [comment]
Still can't reproduce the issue locally.
Feel free to reopen once you have any kind of a sample where it can be peproduced

**Comment by CodeDreamfy** [comment]
> Still can't reproduce the issue locally.
> Feel free to reopen once you have any kind of a sample where it can be reproduced

I have been very embarrassed to reply so long, I finally found the cause of the problem, I guess it is to add {type: 'project'} to the task object when initializing the task, which causes Gantt to not correctly identify the project root category. , limiting the number of gantt renderings, what do you think? When I removed it, there was no limit, and the complete display was made.

**Comment by CodeDreamfy** [comment]
> Still can't reproduce the issue locally.
> Feel free to reopen once you have any kind of a sample where it can be reproduced

Sorry, I just tried it, not that problem. I am not changing the version of 6.1.7 now. However, if I change to 6.2.7, I will record it for you as before. The video is valid for 7 days. Take a look at it.
[demo](https://send.firefox.com/download/36a4d2a78ad63d8f/#cerF-Cz9zr37bNq0YD8seg)

**Comment by wucj21** [comment]
I also encountered the problem of incomplete rendering of the Gantt chart. I tried it. The smart rendering of version 6.2 or above does have problems. If the version 6.2.7 does not set gantt.config.smart_rendering = false, then some data cannot be fully rendered.The following data cannot be rendered normally under the set timescale:
"data":[
        {"id":"10", "text":"Project #1", 
          "render": "split", "start_date":"02-04-2019", "duration":3, "order":10,"progress":0, "open": true},
        {"id":"1", "text":"Task #1",    "start_date":"02-04-2019", "duration":1,  "order":10,"progress":1, "parent":"10"},
        {"id":"2", "text":"Task #2",    "start_date":"06-04-2019", "duration":1,  "order":20,"progress":1, "parent":"10"}
    ],

gantt.config.scales = [
          { unit: 'day', step: 1, format: '%Y-%m-%d' },
          { unit: 'hour', step: 1, date: '%H' }
        ]
