### ISSUE TITLE
Trying to show a new variable in JS

### ISSUE THREAD

**Issue by TD-RA** [DHTMLX/gantt#47]
Hello,

I´m currently trying to implement your gannt in my Laravel project, but when I try to show a multiple select of an array I cant seem to show the data from another table besides task.

for example, if I do this:
`	gantt.templates.leftside_text = function(start, end, users){
			return users.name + " dia";
		};`

It is going to return undifined.

What can it be? I tried everything now...

**Comment by gearcoded** [comment]
Hello,
Gantt is a client-side application, everything you update in the chart occurs on the client-side. The Data Processor helps to connect it with the server-side.
The `leftside_text` template uses the task object as a third parameter:
https://docs.dhtmlx.com/gantt/api__gantt_leftside_text_template.html

So, when you name the third parameter as `users` you just give a different name to the `task` object. You need to implement a custom solution to obtain the data from your table in a variable and use that variable to show the data in the template:
http://snippet.dhtmlx.com/41452f541
