### ISSUE TITLE
DataProcessor doesn't handle rejected promise

### ISSUE THREAD

**Issue by yuriy-harbuzyuk** [DHTMLX/gantt#48]
v6.2.7 _sendData only handles success: `actionPromise.then(_onResolvedCreateUpdate);`
That is why the task row doesn't get "gantt_error" style applied when promise is rejected.

**Comment by gearcoded** [comment]
Hello,
Could you reproduce the issue in one of the following snippets? I will give it to the dev team and they will check what might be wrong:
http://snippet.dhtmlx.com/9d5e85a4a
https://snippet.dhtmlx.com/0763f65c2
After adding your Gantt configuration, try to reproduce the issue, then click on the "Share" button and copy the link.

**Comment by yuriy-harbuzyuk** [comment]
Hello, 
Here you go http://snippet.dhtmlx.com/5/4ac5d5a16
update returns error, thus you can see after update task was marked with bold. Also  "onAfterUpdate" of data processor is never invoked in case of error.

As written in my first post, the issue is in this line of code
`actionPromise.then(_onResolvedCreateUpdate);`

that is located in this method:
`DataProcessor.prototype._sendData`

Explanation: 
the code as you have it defines only "success" callback (one paramentr). "error" callback is not defined (second parameter is missing):
`actionPromise.then(_onResolvedCreateUpdate)`

if you add "error" callback, e.g. add one more handler to "then" like shown below, Gantt would mark unsaved record with red color, and I hope will also invoke "onAfterUpdate" (as stated in  documentation here https://docs.dhtmlx.com/gantt/desktop__server_side.html in "Error handling" section)
`actionPromise.then(_onResolvedCreateUpdate, _onResolvedCreateUpdate);`

**Comment by gearcoded** [comment]
Hello,
Thank you for your suggestion, I forwarded it to the dev team.
Let's continue our discussion in the support system.
