### ISSUE TITLE
Dhtmlx-gantt upgrade to 6.2 or more gantt rendering is incomplete 

### ISSUE THREAD

**Issue by wucj21** [DHTMLX/gantt#49]
I also encountered the problem of incomplete rendering of the Gantt chart. I tried it. The smart rendering of version 6.2 or above does have problems. If the version 6.2.7 does not set gantt.config.smart_rendering = false, then some data cannot be fully rendered.The following data cannot be rendered normally under the set timescale:
"data":[
{"id":"10", "text":"Project #1",
"render": "split", "start_date":"02-04-2019", "duration":3, "order":10,"progress":0, "open": true},
{"id":"1", "text":"Task #1", "start_date":"02-04-2019", "duration":1, "order":10,"progress":1, "parent":"10"},
{"id":"2", "text":"Task #2", "start_date":"06-04-2019", "duration":1, "order":20,"progress":1, "parent":"10"}
],

gantt.config.scales = [
{ unit: 'day', step: 1, format: '%Y-%m-%d' },
{ unit: 'hour', step: 1, date: '%H' }
]

**Comment by gearcoded** [comment]
It is a known issue, and it happens because `Project #1` doesn't have the `project` type. The dev team will fix it in the future, but I cannot give you any ETA.

**Comment by gearcoded** [comment]
Hello,
The dev team fixed the bug when Gantt hid the split task when its parent didn't have the `project` task type:
https://docs.dhtmlx.com/gantt/whatsnew.html#701
You can see how it now works in the following snippet:
http://snippet.dhtmlx.com/7469c747f
