### ISSUE TITLE
Drag timeline clashes with readonly

### ISSUE THREAD

**Issue by Decat-SimonA** [DHTMLX/gantt#51]
Reproduction:
- open https://docs.dhtmlx.com/gantt/samples/02_extensions/27_drag_timeline.html
- set `gantt.config.readonly = true;`
- try to drag and drop tasks, links, change duration of tasks

Those modifications should be impossible since the Gantt is read only. But we can still do it if `dhtmlxgantt_drag_timeline.js` is imported.

**Comment by AlexKlimenkov** [comment]
Hi,
should be fixed in v6.3.1 
https://docs.dhtmlx.com/gantt/whatsnew.html#631
