### ISSUE TITLE
[Question] Is there a way to replace adding/editing task form

### ISSUE THREAD

**Issue by honb** [DHTMLX/gantt#52]
Hi,

I want to replace the standard adding/editing form by a new one with new styling. Is this possible?

Thanks

**Comment by AlexKlimenkov** [comment]
Hi,

sure, you can either customize the default form by adding new controls
https://docs.dhtmlx.com/gantt/desktop__default_edit_form.html#lightboxstructure

Or you can completely replace it by a custom form:
https://docs.dhtmlx.com/gantt/desktop__custom_edit_form.html
