### ISSUE TITLE
Milestone does not render as expected

### ISSUE THREAD

**Issue by honb** [DHTMLX/gantt#53]
Hi guys,

I'm using "dhtmlx-gantt": "^6.3.1"
Just following https://docs.dhtmlx.com/gantt/desktop__milestones.html#specifyingmilestonesinadataset to support milestone but it does not work
![image](https://user-images.githubusercontent.com/26110193/70414667-5eb73f80-1a8d-11ea-9177-9faeb4225b88.png)

![image](https://user-images.githubusercontent.com/26110193/70414499-d89af900-1a8c-11ea-9c08-fd2db80e1a10.png)

Also, I saw the task $rendered_type: "task" while type is milestone
Results:
![image](https://user-images.githubusercontent.com/26110193/70414541-fe280280-1a8c-11ea-9137-14578598eb83.png)

Expect: https://docs.dhtmlx.com/gantt/samples/01_initialization/16_projects_and_milestones.html

**Comment by AlexKlimenkov** [comment]
Hi,
I'm afraid it's a limitation of the free version of the component
https://docs.dhtmlx.com/gantt/desktop__task_types.html

I think the closest thing you can get with the free version, without writing too much code, is customizing some tasks to look like a milestone using the built-in templates:

http://snippet.dhtmlx.com/54e6ff1ff
