### ISSUE TITLE
Missing extension at version 7.0.0

### ISSUE THREAD

**Issue by lecong** [DHTMLX/gantt#57]
Lost extension at lasted version

**Comment by AlexKlimenkov** [comment]
Hi,

this is expected:
https://docs.dhtmlx.com/gantt/migrating.html#6370

Starting from v7.0 extension files are embedded into dhtmlxgantt.js, as well as locales. 
Extensions can be enabled using (gantt.plugins)[https://docs.dhtmlx.com/gantt/api__gantt_plugins.html] method:

```
gantt.plugins({
   tooltip: true,
   auto_scheduling: true
});


...

gantt.init(container);
```

https://docs.dhtmlx.com/gantt/desktop__extensions_list.html

If you have a custom extension file that you add to the page after dhtmlxgantt.js - it will continue to work. If you use built-in extensions - they have to be enabled via (gantt.plugins)[https://docs.dhtmlx.com/gantt/api__gantt_plugins.html]
