### ISSUE TITLE
Angular 9 problems - Gantt is not defined

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [DHTMLX/gantt#58]
We're using DHTMLXGantt pro version within Angular application. It used to work fine for some time, but after updating angular from 8 to 9 (Ivy is **disabled**) I'm getting the following error in runtime:
```
Uncaught ReferenceError: Gantt is not defined
    at Object../node_modules/@pdtec/dhtmlx-gantt-pro/codebase/locale/locale_de.js (index.ts:132)
```
It displays no errors with Angular8.

*The DHTMLXGantt library is called `@pdtec/dhtmlx-gantt-pro` because we pack downloaded sources into our private repository under `@pdtec/dhtmlx-gantt-pro` name.*

The gantt sources are imported into main app component:
```ts
import { Component, ElementRef, Inject, Input, OnDestroy, OnInit, Optional, ViewChild, ViewEncapsulation } from '@angular/core';
import '@pdtec/dhtmlx-gantt-pro';
import '@pdtec/dhtmlx-gantt-pro/codebase/ext/dhtmlxgantt_auto_scheduling';
import '@pdtec/dhtmlx-gantt-pro/codebase/ext/dhtmlxgantt_grouping';
import '@pdtec/dhtmlx-gantt-pro/codebase/ext/dhtmlxgantt_marker';
import '@pdtec/dhtmlx-gantt-pro/codebase/ext/dhtmlxgantt_undo';
(...)
@Component({
    encapsulation: ViewEncapsulation.None, // to be able to style the diagram
    selector: 'marble-gantt-diagram',
    styleUrls: ['./ng-gantt-diagram.component.scss'],
    templateUrl: './ng-gantt-diagram.component.html'
})
export class MarbleGanttDiagramComponent implements OnInit, OnDestroy {
    (...)
}
```
I already tried importing it into main app *.module* file, but it does not fix the error.

This does not seems to be related to any specific DHTMLXGantt version.

Could you please help us out solving the issue?

**Comment by gearcoded** [comment]
Hello,
Gantt should work correctly in Angular 8 and 9:
https://files.dhtmlx.com/30d/809e9c17294696e33153bc7f0cad4c59/angular8+gantt_6.3.2.zip
https://files.dhtmlx.com/30d/2fdb4682c4edbdb2d85ff59efd3df5ba/angular9+gantt_7.0.1.zip

It is hard to suggest what might be wrong in your case.
Please, send me a ready demo where I can reproduce the issue, and I will check what might be wrong there.

**Comment by Melmoth-the-Wanderer** [comment]
Months have passed since I reported the problem and now, long after angular 9 is released, the problem seems to be fixed. It builds and works fine, I haven't changed anything in my code. Thanks @gearcoded for confirming this is not bug with the library.
