### ISSUE TITLE
Missing component function

### ISSUE THREAD

**Issue by tenkiss258** [DHTMLX/gantt#59]
Recently, using this component, we found that there is no toolip and no Chinese package. How can I download these packages.

**Comment by gearcoded** [comment]
Hello,
Starting from the 7.0 version, the extension and localization files are included in the `dhtmlxgantt.js` file:
https://docs.dhtmlx.com/gantt/whatsnew.html#x4602x70x4603x
To enable extensions, you need to use the `plugins` method:
https://docs.dhtmlx.com/gantt/api__gantt_plugins.html
To switch the locale, you need to use the `gantt.i18n.setLocale` method:
https://docs.dhtmlx.com/gantt/desktop__localization.html#activatingalocale

You can read more about migrating from earlier versions:
https://docs.dhtmlx.com/gantt/migrating.html#6370
