### ISSUE TITLE
there is no dhtmlxgantt_grouping.js file in extensions

### ISSUE THREAD

**Issue by grabus** [DHTMLX/gantt#6]
But it is in the demo
http://docs.dhtmlx.com/gantt/samples/02_extensions/08_tasks_grouping.html

**Comment by AlexKlimenkov** [comment]
The task grouping feature is not included into a free edition which is published here
http://dhtmlx.com/docs/products/dhtmlxGantt/
Demos on site uses the Pro version of gantt
