### ISSUE TITLE
Is there any Python module for interfacing with the library ? 

### ISSUE THREAD

**Issue by fcabaud** [DHTMLX/gantt#61]
Hello

In order to use DHTMLX/Gantt javascript library in python, is there any python module ?

Best regards

**Comment by gearcoded** [comment]
Hello,
DHTMLX Gantt doesn't have any integration with Python and we don't have any modules for it. But if you can show an HTML page in your project, you should be able to add Gantt there.
Here is a simple demo for Django:
https://files.dhtmlx.com/30d/7bca9a76ffb8201f9914e7afa036bfed/django+gantt.zip
