### ISSUE TITLE
not support realStartDate and realEndDate?

### ISSUE THREAD

**Issue by lxv543** [DHTMLX/gantt#62]

**Comment by gearcoded** [comment]
Hello,
Gantt uses the `start_date` and `end_date` properties as the date parameters:
https://docs.dhtmlx.com/gantt/desktop__loading.html#dataproperties
You can add the `realStartDate` and `realEndDate` as custom properties. Or you can set the `start_date` and `end_date` properties from the `realStartDate` and `realEndDate` properties.
Here is an example of how it might be implemented:
http://snippet.dhtmlx.com/5/a6e57057a

If you need something different, please, describe your question in more detail.
