### ISSUE TITLE
Scales are not displayed with latest Chrome

### ISSUE THREAD

**Issue by tigrenok00** [DHTMLX/gantt#63]
Hi guys,

I'm using gantt with RTL config and hebrew locale (he). We noticed that on latest version of Chrome (Version 87.0.4280.141 (Official Build) (64-bit)) the time scales suddenly stopped displaying. Also, when scrolling to the left, the grid_data area dissapears. 
On older version of chrome (Version 78.0.3904.87 (Official Build) (64-bit)) everything works perfectly.
I've upgraded to latest gantt version but this had no impact.

Attaching screenshots of working example and the current one (same code on different chrome versions) - please help me figure out how this could be fixed?

Not working:
![image](https://user-images.githubusercontent.com/23075641/108690756-6385d900-7503-11eb-94ba-83d93483d4fa.png)

Older chrome:
![image](https://user-images.githubusercontent.com/23075641/108690818-79939980-7503-11eb-8039-bf33a1e6d58d.png)

**Comment by tigrenok00** [comment]
Another note, when I'm inspecting the first element of the scale (the right-most, the one that is supposed to be first in RTL and currently not seen because of the problem), I can see via the date that it is not the earlies date like should be but the latest one:

![image](https://user-images.githubusercontent.com/23075641/108693680-c9c02b00-7506-11eb-9645-89b108653e5f.png)

**Comment by tigrenok00** [comment]
Update:

Setting `gantt.config.smart_scales = false` (was true before) made the scale labels appear, but they still go from left to right, not the other way around (the tasks themselves go from right to left):

![image](https://user-images.githubusercontent.com/23075641/108704964-5bcf3000-7515-11eb-8f3d-d8c62860f312.png)

**Comment by tigrenok00** [comment]
I had to set this in order to fix the scale labels (direction LTR, the opposite of what should be):
`.gantt_task_scale{
  direction: ltr !important;
}`
Any idea why were those changes necessary when the only change in the environment was chrome version?
I'm leaving this in case anyone else has the same problem, or if we discover more issues.

**Comment by gearcoded** [comment]
@tigrenok00, I couldn't reproduce the issue in the following snippet:
http://snippet.dhtmlx.com/5/d6e76697c
http://prnt.sc/12iu5b3

Probably, it is related to the Gantt configuration, but it is hard to suggest what might be wrong as I don't see your code.
Please, add your configuration in the following snippet and make sure that the issue is reproduced there:
https://snippet.dhtmlx.com/38ee1b370
Then, click on the `Share` button and send me the link.
Or send me a ready demo with all the necessary Javascript and CSS files so that I can reproduce the issue locally.

**Comment by ZedCoding** [comment]
@tigrenok00  how do you arrange tasks horizontally? forward to your reply

**Comment by gearcoded** [comment]
@ZedCoding,
To show several tasks on the same row, you need to use the `Split Tasks` feature:
https://docs.dhtmlx.com/gantt/desktop__split_tasks.html
Here are examples of how it works:
https://docs.dhtmlx.com/gantt/samples/04_customization/11_split_task.html
https://docs.dhtmlx.com/gantt/samples/04_customization/21_open_split_task.html
