### ISSUE TITLE
asynchronous

### ISSUE THREAD

**Issue by bailuweishuang** [DHTMLX/gantt#64]
Hello. I want to do the following. How do I do it；‘onBeforeTaskDrag’， How does this method support asynchronous operations, which seems to be not working right now；
![image](https://user-images.githubusercontent.com/24244087/109093921-27958280-7754-11eb-9947-145f007d7b0a.png)

**Comment by gearcoded** [comment]
@bailuweishuang, right now, Gantt doesn't support asynchronous event handlers. The dev team will add that feature in the future, but I cannot give you any ETA.

For now, you need to call the `_this.getMessage` function before the `onBeforeTaskDrag` event handler.
