### ISSUE TITLE
the task has no start_time, just creat task

### ISSUE THREAD

**Issue by JerryWang24** [DHTMLX/gantt#68]
At the beginning of the task list, only the name is displayed, and the start time is not filled in. Only the task is created. Only operate in Gantt chart when necessary. Can we do that?

**Comment by gearcoded** [comment]
@JerryWang24, Each regular task should have at least 2 date parameters: `start_date`, `end_date`, `duration`. When a regular task doesn't have those parameters, it should be unscheduled:
https://docs.dhtmlx.com/gantt/desktop__unscheduled_tasks.html
Here is an example:
http://snippet.dhtmlx.com/5/e07601c7f
