### ISSUE TITLE
the license GPL-2.0 dose not work

### ISSUE THREAD

**Issue by ahua52** [DHTMLX/gantt#69]
## how to solve the problem if I do not buy Commercial/Enterprise or Ultimate license 
thank you!

![2441620710325_ pic_hd](https://user-images.githubusercontent.com/19704104/117762321-7cc53880-b25b-11eb-95f4-fc2b92f98fc6.jpg)
![2411620707784_ pic_hd](https://user-images.githubusercontent.com/19704104/117762335-82bb1980-b25b-11eb-8147-0275d273bfb0.jpg)

**Comment by gearcoded** [comment]
@ahua52, it seems that you have the Trial version connected somewhere on your page. Other versions don't have the code that adds these popup messages. You need to check all your files for the Trial version of the `dhtmlxgantt.js` file.
Also, starting from the 7.1 version, that popup message is only displayed in the top right corner, it not longer spams the whole right side.
