### ISSUE TITLE
Show All Scale, Show work days only, Show office hours buttons are not working

### ISSUE THREAD

**Issue by ypapouin** [DHTMLX/gantt#71]
Visible in multiple samples, these buttons are not doing anything.

![image](https://user-images.githubusercontent.com/22446243/119847898-a6dd5280-bf0b-11eb-814f-29984cd42b09.png)

**Comment by gearcoded** [comment]
@ypapouin, I couldn't reproduce that in our samples. 
Here is the video that demonstrates how the buttons work:
https://files.dhtmlx.com/30d/06f2a9a1ef0e6c3324b88a0482122f61/vokoscreen-2021-09-06_14-38-41.mkv
