### ISSUE TITLE
lightbox doesn‘t show Custom fields

### ISSUE THREAD

**Issue by adadale** [DHTMLX/gantt#72]
{name:"description", height:38, map_to:"text", type:"textarea",focus:true},
    {name:"user_name", height:38, map_to:"user_name", type:"select",focus:true,options: [ 
        {key:1, label: "High"},                                               
        {key:2, label: "Normal"},                                             
        {key:3, label: "Low"}                                                 
     ]},
    {name:"group_name", height:22, map_to:"group_name",type:"select",focus:true},                                                                        
    {name:"time", height:72, type:"duration", map_to:"auto"}
];
user_name doesn't show and it shows undefined  and i want to ask how to send request to server when i click the select of user_name
![image](https://user-images.githubusercontent.com/30455538/122512464-76d12d00-d03b-11eb-91cf-472ebc3eb8d4.png)

**Comment by gearcoded** [comment]
@adadale, 
> user_name doesn't show and it shows undefined

Lightbox doesn't use the `name` parameter in the section configuration to display the section name. You need to define it in the section label:
```
gantt.locale.labels.section_user_name
```
https://docs.dhtmlx.com/gantt/desktop__textarea.html#initialization

Here is the snippet:
http://snippet.dhtmlx.com/5/ebf6f038e


----------------------------

> i want to ask how to send request to server when i click the select of user_name

Gantt doesn't have a built-in way to send a request to the server when you change something in the lightbox. Also, there is no built-in event handler that fires when you change the value of the select section.
You will need to implement a custom solution by using the Gantt API and Javascript.

For example, you can manually attach an event in the `onLightbox` event handler:
https://docs.dhtmlx.com/gantt/api__gantt_onlightbox_event.html
To send the changes to the server, you can use the built-in AJAX module:
https://docs.dhtmlx.com/gantt/api__gantt_ajax_other.html

Here is an example of how it might be implemented:
http://snippet.dhtmlx.com/5/7d6e7ebad
https://snipboard.io/T6bXd8.jpg
