### ISSUE TITLE
Un-minify skins css

### ISSUE THREAD

**Issue by Aarbel** [DHTMLX/gantt#73]
Cf https://github.com/DHTMLX/gantt/blob/master/codebase/skins/dhtmlxgantt_material.css

All your css examples are minified, would be great to be able to read them / copy them easily ;)

**Comment by gearcoded** [comment]
Here is the unminified CSS file with a few comments:
https://github.com/DHTMLX/gantt/blob/master/codebase/sources/dhtmlxgantt.css
