### ISSUE TITLE
Throwing error 0x800a138f - JavaScript runtime error: Unable to get property '-1' of undefined or null reference

### ISSUE THREAD

**Issue by anik123** [DHTMLX/gantt#8]
I am using `dhtmlxGantt v.4.0.0 Stardard`

When add this config 

```
gantt.config.show_chart = false;

```

This error is throwing in the library file

> - 0x800a138f - JavaScript runtime error: Unable to get property '-1' of undefined or null reference

At this moment i am working by adding this line in the library 

```
    if (!gantt.config.show_chart)
        return;
```

In this method

```
gantt.showDate = function (date) {
    if (!gantt.config.show_chart)
        return;
    var date_x = this.posFromDate(date);
    var scroll_to = Math.max(date_x - this.config.task_scroll_offset, 0);
    this.scrollTo(scroll_to);
};

```

Any fix for this ?

**Comment by AlexKlimenkov** [comment]
Thanks, I've reproduced the issue.
We're going to push a fix-update near time, it will contain this fix as well.
