### ISSUE TITLE
Error in callback for watcher "tasks": "TypeError: Cannot read properties of undefined (reading 'length')"

### ISSUE THREAD

**Issue by leoleor** [DHTMLX/gantt#82]
>
![微信图片_20220718102749](https://user-images.githubusercontent.com/56668780/179436913-d271dc1b-49d9-480f-8008-eb037990046f.png)
I don't know what happened. It crashes when you open it

**Comment by gearcoded** [comment]
@leoleor, it is hard to suggest what might be wrong in your case as I don't see your code. You can share a ready demo with all the necessary files. I will run it and check what actually happens there.
