### ISSUE TITLE
Unable to Purchase license 

### ISSUE THREAD

**Issue by gdotp01** [DHTMLX/gantt#84]
I'm not sure if this is the right place to ask the question but after trying emails, help forms and the Canada based help desk (3 times) i'm not sure where else to ask.

We are trying to purchase the Gannt license (enterprise) for my company, a large financial products/exchange company but due to our purchase policies this can only be done via a PO process. To do this I need to set up DHTMLX/Payproglobal as a company on our purchasing systems to get a  PO number to make the purchase through the Payproglobal run online purchase site.  So far I've rung the help desk three times and been asked to email another part of Payproglobal to get the necessary information we need (accounts@payproglobal.com) and we have had no reply to any of these emails.  We have supplied Payproglobal a telephone number to ring and not had a call back. 

Does anyone here know how we can get around this issue, or have any influence on getting Payproplobal to respond to our request for information?

**Comment by gearcoded** [comment]
@gdotp01, I informed the Sales team about your use case, but it seems that the issue has been resolved.

**Comment by gdotp01** [comment]
Yes thanks . I think we ate sorted now
