### ISSUE TITLE
Inline Editors not working after component destroy in Angular

### ISSUE THREAD

**Issue by AntoRin** [DHTMLX/gantt#86]
**Dhtmlx-gantt version**: 7.1.13

I am using the free version of dhtmlx-gantt. This means that I won't be able to initialize a new gantt instance on component render. I perform some clean-up of the gantt instance on destroy, which is mostly removing all events and tooltips. Although this has been working well so far, the inline editors only work the first time. After the first time, none of the events related to the inline events fire (events that are created using the gantt.ext.inlineEditors.attachEvent method).

**Comment by AntoRin** [comment]
I've found out that using the gantt.init method on an already initialized gantt instance makes the inline editors unusable. 

Any workarounds for this?

**Comment by gearcoded** [comment]
@AntoRin,
It is a bug in Gantt that the inline editor events stop working after using the `init` and `resetLayout` methods. The dev team will fix the bug in the future, but I cannot give you any ETA.

As a workaround, you can detach events and attach them again in the `onGanttReady` event handler:
```
var onSave_id = null;
gantt.attachEvent("onGanttReady", function () {
  if (onSave_id) gantt.ext.inlineEditors.detachEvent(onSave_id)

  onSave_id = gantt.ext.inlineEditors.attachEvent("onSave", function (state) {
    gantt.message("onSave event");
    var col = state.columnName;
    if (gantt.autoSchedule && (col == "start_date" || col == "end_date" || col == "duration")) {
      gantt.autoSchedule();
    }
  });
});
```
Here is the snippet:
https://snippet.dhtmlx.com/5/a6ca5c108

**Comment by AntoRin** [comment]
Hi, @gearcoded, thanks for the reply.

This solution works. Although I was already detaching inline editor events when the component destorys, I wasn't attaching them back during the onGanttReady event. Apparently, that's necessary.

And for those who are referring to this later on, you can use the following method to detach all events from the inline editor instead of having to store reference to each event using the returned event ID and detaching them one by one.

`gantt.ext.inlineEditors.detachAllEvents();`

**Comment by CedricHg** [comment]
> @AntoRin, It is a bug in Gantt that the inline editor events stop working after using the `init` and `resetLayout` methods. The dev team will fix the bug in the future, but I cannot give you any ETA.
> 
> As a workaround, you can detach events and attach them again in the `onGanttReady` event handler:
> 
> ```
> var onSave_id = null;
> gantt.attachEvent("onGanttReady", function () {
>   if (onSave_id) gantt.ext.inlineEditors.detachEvent(onSave_id)
> 
>   onSave_id = gantt.ext.inlineEditors.attachEvent("onSave", function (state) {
>     gantt.message("onSave event");
>     var col = state.columnName;
>     if (gantt.autoSchedule && (col == "start_date" || col == "end_date" || col == "duration")) {
>       gantt.autoSchedule();
>     }
>   });
> });
> ```
> 
> Here is the snippet: https://snippet.dhtmlx.com/5/a6ca5c108

This snippet no longer works on the current version of DHTMLX Gantt, because the attachEvent function for InlineEditorEvents now returns a boolean rather than a string id. I have not yet been able to find how I can get this id in the current version for detaching purposes.

**Comment by AntoRin** [comment]
> > @AntoRin, It is a bug in Gantt that the inline editor events stop working after using the `init` and `resetLayout` methods. The dev team will fix the bug in the future, but I cannot give you any ETA.
> > As a workaround, you can detach events and attach them again in the `onGanttReady` event handler:
> > ```
> > var onSave_id = null;
> > gantt.attachEvent("onGanttReady", function () {
> >   if (onSave_id) gantt.ext.inlineEditors.detachEvent(onSave_id)
> > 
> >   onSave_id = gantt.ext.inlineEditors.attachEvent("onSave", function (state) {
> >     gantt.message("onSave event");
> >     var col = state.columnName;
> >     if (gantt.autoSchedule && (col == "start_date" || col == "end_date" || col == "duration")) {
> >       gantt.autoSchedule();
> >     }
> >   });
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is the snippet: https://snippet.dhtmlx.com/5/a6ca5c108
> 
> This snippet no longer works on the current version of DHTMLX Gantt, because the attachEvent function for InlineEditorEvents now returns a boolean rather than a string id. I have not yet been able to find how I can get this id in the current version for detaching purposes.

Hey, @CedricHg, thanks for the reply. I have been using this solution for a while now following @gearcoded  's advice. Seems to be working fine. Although let me know when this is totally resolved.

**Comment by AntoRin** [comment]
@gearcoded, appreciate that. Thank you.

**Comment by gearcoded** [comment]
**@AntoRin**,
The dev team fixed the bug with the inline editor events. Now, they are not removed after the `init` and `resetLayout` methods:
https://docs.dhtmlx.com/gantt/whatsnew.html#:~:text=Prevent%20Inline%20Editors%20events%20from%20being%20removed%20after%20reinitializing%20Gantt%20or%20resetting%20the%20layout

You can see that the bug is no longer reproduced in the following sample:
http://snippet.dhtmlx.com/5/34e5e5ba4

**Comment by AntoRin** [comment]
> **@AntoRin**,
> The dev team fixed the bug with the inline editor events. Now, they are not removed after the `init` and `resetLayout` methods:
> https://docs.dhtmlx.com/gantt/whatsnew.html#:~:text=Prevent%20Inline%20Editors%20events%20from%20being%20removed%20after%20reinitializing%20Gantt%20or%20resetting%20the%20layout
> 
> You can see that the bug is no longer reproduced in the following sample:
> http://snippet.dhtmlx.com/5/34e5e5ba4
> 

Thank you!
