### ISSUE TITLE
Api methods missing

### ISSUE THREAD

**Issue by wufe-natuku** [DHTMLX/gantt#9]
According to the documentation, there is a toggleTaskSelection method and a isSelectedTask method and neither are marked as pro only. Both appear to be missing from the actual code for the most recent release.

[isTaskSelected](http://docs.dhtmlx.com/gantt/api__gantt_isselectedtask.html)
[toggleTaskSelection](http://docs.dhtmlx.com/gantt/api__gantt_toggletaskselection.html)

**Comment by AlexKlimenkov** [comment]
Hello,
these methods are defined in dhtmlxgantt_multiselect.js extension, not in the core dhtmlxgantt.js
http://docs.dhtmlx.com/gantt/desktop__multiselection.html
We'll mark them in API reference somehow, thanks.
