### ISSUE TITLE
Issue with DHTMLX Connector

### ISSUE THREAD

**Issue by ArnaudBOc** [DHTMLX/gantt#91]
Hi all,

Before my migration on PHP 7 I was using DHTMLX with mysql and it as working well. My grids were loading perfectly through the connector. Now, I have changed in db_common to myqli instead of mysql and my grids are not loading at all.

Do you have any ideas please ?

**Comment by gearcoded** [comment]
@ArnaudBOc,
It is hard to suggest what might be wrong as I don't see your code.

Please send me a ready demo with all the necessary JavaScript and CSS files so that I can reproduce the issue locally.
